---
###################################################################
#
#  Ubuntu Trusty 64-bit management routines
#
#################################################################### 
- name: update debian packaging tools
  apt:
    pkg={{ packages }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
    autoremove=yes
  when: build_deb_packages
  vars:
    packages:
      - devscripts
      - debian-archive-keyring
      - equivs
      - aptitude
      - po4a
      - debhelper
      - autopoint
      - libelf-dev
      - libdevel-cover-perl
      - autoconf
      - automake
      - automake
      - libtool
      
- name: add apt-keys for sid
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 8B48AD6246925553
    - 7638D0442B90D010
      
#- name: add apt-keys for sid
#  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys {{ item }}
#  with_items:
#    - 8B48AD6246925553
#    - 7638D0442B90D010
    
- name: add stretch source repository to apt sources
  apt_repository:
    repo:  deb-src http://ftp.us.debian.org/debian stretch main contrib non-free
    state: present
    filename: stretch-src
    
- name: add sid source repository to apt sources
  apt_repository:
    repo:  deb-src http://ftp.us.debian.org/debian sid main contrib non-free
    state: present
    filename: sid-src

- name: create workspace
  file:
    path: ~/workspace
    state: directory
  become_user: vagrant

- name: assure build script present
  template:
    src: build-celery-deps.sh
    dest: /usr/local/bin/build-celery-deps
    mode: 0755
  
