---
# Variables for OCR role
src_directory: /tmp/ocr
tessdata_prefix: /usr/local/share
tessdata_directory: "{{ tessdata_prefix }}/tessdata"

tesseract_version: "3.04.01"
tesseract_url: https://github.com/tesseract-ocr/tesseract/archive/{{ tesseract_version }}.tar.gz

tessdata_version: "master"
tessdata_url: https://github.com/tesseract-ocr/tessdata/raw/{{ tessdata_version }}/

leptonica_version: "1.73"
leptonica_url: https://github.com/DanBloomberg/leptonica/archive/v{{ leptonica_version }}.tar.gz

# seems they removed all the cube files? not sure what they were for anyways.
default_language: eng
tesseract_lang_data:
  - "{{ default_language }}.traineddata"
