---
# Variables for Redis role
redis_install_directory: /opt/redis
redis_run_directory: /var/redis/6379
redis_log_directory: /var/log/redis
redis_archive: http://download.redis.io/redis-stable.tar.gz
