---
###################################################################
#
#  Postgres service role
#
###################################################################
- name: install postgres via apt-get
  become_user: root
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
    pkg:
      - postgresql-{{ postgresql_version }}
      - postgresql-contrib-{{ postgresql_version }}
      - python-psycopg2

# Do this first before we change pg_hba.conf so we can guarantee we have the right password.
- name: configure postgres super user
  become_user: postgres
  postgresql_user:
    name=postgres
    password="{{ pg_password }}"
    login_password="{{ pg_password }}"

- name: configure postgres using template file
  become_user: root
  template:
    src=pg_hba.conf
    dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

- name: make sure postgresql is running and set to start on restart
  become_user: root
  service:
    name: postgresql
    state: started
    enabled: yes

- name: set up .pgpass for {{ pg_user }}
  become_user: "{{ pg_user }}"
  template:
    src=pgpass
    dest=/home/{{ pg_user }}/.pgpass

- name: make .pgpass private
  become_user: "{{ pg_user }}"
  file:
    path=/home/{{ pg_user }}/.pgpass
    owner={{ pg_user }}
    group={{ pg_user }}
    mode=0600

- include: postgres-accounts.yml

- name: bounce postgres
  become_user: root
  service:
    name: postgresql
    state: restarted
    enabled: yes
