---
###################################################################
#
#  Base debian setup
#
####################################################################

- name: install schroot packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
    pkg:
      - schroot
      - debootstrap
      - git-buildpackage
      - ccache
      - libeatmydata1
      - sbuild
      - reprepro
      - pgpdump
      
- name: import get-keys tasks
  import_tasks: get-keys.yml

- name: import reprepro tasks
  import_tasks: reprepro.yml

- name: import source-repo tasks
  import_tasks: source-repos.yml
  
- name: add vagrant user to sbuild group
  user:
    name: vagrant
    groups: sbuild
    append: true
    
- name: add .sbuildrc for vagrant user
  become_user: vagrant
  template:
    src: sbuildrc
    dest: /home/vagrant/.sbuildrc

- name: create logs directory
  become_user: vagrant
  file:
    state: directory
    path: "{{ build_log_dir }}"
    
- name: setup schroot_roots_directory
  file:
    path: "{{ schroot_roots_directory }}"
    state: directory

- name: configure schroot default copyfiles
  template:
    src: schroot-default-copyfiles
    dest: /etc/schroot/default/copyfiles
  when: use_apt_cache

- name: use apt proxy in sbuild chroot
  lineinfile:
    dest: /etc/schroot/sbuild/copyfiles
    line: /etc/apt/apt.conf.d/000apt-cacher-ng-proxy
  when: use_apt_cache

- name: add bind mounts to sbuild chroot
  lineinfile:
    dest: /etc/schroot/sbuild/fstab
    line: "{{ item }}"
  with_items:
    - /home /home none rw,bind 0 0
    - /vagrant /vagrant none rw,bind 0 0
    
- name: create xenial chroot 
  command:
  args:
    argv:
      - sbuild-createchroot
      - --include=eatmydata,ccache,gnupg
      - xenial
      - xenial
      - http://archive.ubuntu.com/ubuntu
    chdir: "{{ schroot_roots_directory }}"
    creates: "{{ schroot_roots_directory }}/xenial"
  register: sbuild_chroot_created
  when: not use_apt_cache

- name: create xenial chroot (using apt-cache proxy)
  command:
  args:
    argv:
      - sbuild-createchroot
      - --include=eatmydata,ccache,gnupg
      - xenial
      - xenial
      - http://archive.ubuntu.com/ubuntu
    chdir: "{{ schroot_roots_directory }}"
    creates: "{{ schroot_roots_directory }}/xenial"
  environment:
    http_proxy: "{{ aptproxy }}"
  register: sbuild_chroot_created
  when: use_apt_cache

- name: copy sources.list to sbuild chroot
  copy:
    src: /etc/apt/sources.list
    dest: "{{ schroot_roots_directory }}/xenial/etc/apt/sources.list"

- name: copy source repo lists to sbuild chroot
  copy:
    src: "/etc/apt/sources.list.d/{{ item }}"
    dest: "{{ schroot_roots_directory }}/xenial/etc/apt/sources.list.d/{{ item }}"
  with_items:
    - bionic-main.list
    - bionic-universe.list
    - bionic-multiverse.list
    
- name: copy local sources.list to sbuild chroot
  template:
    src: local-apt-source
    dest: "{{ schroot_roots_directory }}/xenial/etc/apt/sources.list.d/local.list"

- name: import local apt key to sbuild chroot
  become_user: vagrant
  shell: gpg --export | sudo schroot -u root -c source:xenial-amd64-sbuild apt-key add -

- name: update sbuild chroot
  shell: sbuild-update -udcar xenial-amd64-sbuild
  when: sbuild_chroot_created is defined
  
  
