---
###################################################################
#
#  Import insecure keys for apt repo
#
####################################################################
- name: check for .gnupg pubring
  become_user: vagrant
  stat:
    path: ~/.gnupg/pubring.gpg
  register: pubring

- name: debug pubring
  debug:
    msg: "pubring {{ pubring }}"

- name: create pubring
  become_user: vagrant
  shell: gpg --list-keys
  args:
    creates: ~/.gnupg/pubring.gpg
  register: pubring
    

- name: debug pubring
  debug:
    msg: "pubring {{ pubring }}"

- name: check if keys present
  become_user: vagrant
  shell: gpg --list-keys
  register: have_keys
  when: pubring

- name: debug check keys present
  debug:
    msg: "have_keys {{ have_keys.stdout }}"
    
- name: list keys
  become_user: vagrant
  shell: gpg --list-keys | grep pub | awk '{print $2}' | grep /
  register: keylist
  when: false

- name: import insecure keys
  become_user: vagrant
  shell: curl {{ item }} | gpg --import
  when: not have_keys.stdout
  loop:
    - "{{ insecure_pubkey_url }}"
    - "{{ insecure_privkey_url }}"
    
