---
###################################################################
#
#  Celery service role
#
###################################################################
- name: import build celery deps
  import_tasks: build-celery.yml
  


- name: prepare Celery directories
  become_user: root
  command: mkdir -p {{ item }}
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ run_directory }}"
    - "{{ log_directory }}"

- name: setup ownership for Celery directories
  become_user: root
  file:
    path="{{ item }}"
    owner="{{ celery_user }}"
    group="{{ celery_user }}"
  with_items:
    - "{{ run_directory }}"
    - "{{ log_directory }}"

- name: install Celery via pip
  become_user: "{{ celery_user }}"
  pip: name=Celery virtualenv={{ virtualenv_directory }}

- name: install Celery daemon config
  become_user: root
  template: src=celeryd.sysv dest=/etc/init.d/celeryd mode=0755

- name: add logrotate settings
  become_user: root
  template: src=celery.logrotate dest=/etc/logrotate.d/celery

- name: start Celery service
  become_user: root
  service:
    name: celeryd
    state: started
    enabled: yes
