---
###################################################################
#
#  Celery service role
#
###################################################################
#- name: import build celery deps
#  import_tasks: build-celery.yml
  


- name: prepare Celery directories
  become_user: root
  command: mkdir -p {{ item }}
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ run_directory }}"
    - "{{ log_directory }}"

- name: setup ownership for Celery directories
  become_user: root
  file:
    path="{{ item }}"
    owner="{{ celery_user }}"
    group="{{ celery_user }}"
  with_items:
    - "{{ run_directory }}"
    - "{{ log_directory }}"

- name: install Celery via pip
  become_user: "{{ celery_user }}"
  pip: name=Celery virtualenv={{ virtualenv_directory }}

- name: install Celery daemon config
  become_user: root
  template: src=celeryd.sysv dest=/etc/init.d/celeryd mode=0755
  when: false

- name: celery config files
  become_user: root
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: celery.conf
      dest: /etc/default/celery
    - src: celery.service
      dest: /etc/systemd/system/celery.service
    - src: celery.tmpfiles
      dest: /etc/tmpfiles.d/celery.conf
    - src: celery.logrotate
      dest: /etc/logrotate.d/celery

- name: start Celery service
  become_user: root
  systemd:
    name: celery
    state: started
    enabled: yes
    
  #service:
  #  name: celeryd
  #  state: started
  #  enabled: yes
  
