---
###################################################################
#
#  OCR service role
#
###################################################################
- name: install required packages via apt-get
  become_user: root
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
    pkg:
      - imagemagick
      #- libpng12-dev
      - autoconf
      - automake
      - libtool
      - pkg-config
      #- libtiff5-dev
      #- libjpeg8-dev
      - libleptonica-dev
      - leptonica-progs
      - tesseract-ocr
      
- name: basic check to see if tesseract and leptonica are available
  become_user: "{{ ocr_user }}"
  command: tesseract -v
  register: result
  ignore_errors: True

- debug: var=result verbosity=0

- name: set "ocr installed" facts
  set_fact:
    leptonica_fullname: "leptonica-{{ leptonica_version }}"
    tesseract_output: "tesseract {{ tesseract_version }}"

- name: running tesseract playbook
  include: tesseract.yml
  #when: not result.failed an tesseract_output in result.stdout
  when: false
