########################
#  Install Tesseract
########################
---
- debug: msg="Configuring Tesseract v{{ tesseract_version}}..."

- name: "create tessdata directory if it doesn't exist"
  become_user: root
  file:
    state=directory
    path="{{ tessdata_directory }}"

- name: download tessdata for our default language
  become_user: root
  get_url:
    url="{{ tessdata_url }}/{{ item }}"
    dest="{{ tessdata_directory }}"
  with_items: "{{ tesseract_lang_data }}"

- name: deploy custom legal english traineddata file
  become_user: root
  copy:
    src=eng.traineddata
    dest="{{ tessdata_directory }}"
    force=yes

- name: set environment variable for TESSDATA_PREFIX
  become_user: root
  lineinfile:
    dest=/etc/environment
    line="TESSDATA_PREFIX={{ tessdata_prefix }}"
    state=present
