########################
#  Install Tesseract
########################
---
- debug: msg="Installing Tesseract v{{ tesseract_version}}..."

- name: configure ocr build directory
  become_user: root
  file:
    state=directory
    path="{{ src_directory }}"
    owner="{{ ocr_user }}"
    group="{{ ocr_user }}"

- name: download and unpack tesseract
  become_user: "{{ ocr_user }}"
  unarchive:
    src="{{ tesseract_url }}"
    dest="{{ src_directory }}"
    copy=no
    owner="{{ ocr_user }}"
    group="{{ ocr_user }}"
    creates="tesseract-{{ tesseract_version }}"


- name: configure tesseract source
  become_user: "{{ ocr_user }}"
  command: "{{ item }}"
  args:
    chdir: "{{ src_directory }}/tesseract-{{ tesseract_version }}"
    creates:
      - "{{ src_directory }}/tesseract-{{ tesseract_version }}/Makefile"
  with_items:
    - ./autogen.sh
    - ./configure
  
- name: make tesseract
  become_user: "{{ ocr_user }}"
  command:
  args:
    argv:
      - make
      - -j2
    chdir: "{{ src_directory }}/tesseract-{{ tesseract_version }}"
    creates:
      - "{{ src_directory }}/tesseract-{{ tesseract_version }}/api/tesseract"

- name: install tesseract
  become_user: root
  command: "{{ item }}"
  args:
    chdir: "{{ src_directory }}/tesseract-{{ tesseract_version }}"
    creates:
      - /usr/local/bin/tesseract
      - /usr/local/lib/libtesseract.so
  with_items:
    - make install
    - ldconfig

- name: "create tessdata directory if it doesn't exist"
  become_user: root
  file:
    state=directory
    path="{{ tessdata_directory }}"

- name: download tessdata for our default language
  become_user: root
  get_url:
    url="{{ tessdata_url }}/{{ item }}"
    dest="{{ tessdata_directory }}"
  with_items: "{{ tesseract_lang_data }}"

- name: deploy custom legal english traineddata file
  become_user: root
  copy:
    src=eng.traineddata
    dest="{{ tessdata_directory }}"
    force=yes

- name: set environment variable for TESSDATA_PREFIX
  become_user: root
  lineinfile:
    dest=/etc/environment
    line="TESSDATA_PREFIX={{ tessdata_prefix }}"
    state=present
