---
###################################################################
#
#  Juriscraper extra requirements for CL testing
#
###################################################################
- name: install selenium
  become_user: "{{ cl_user }}"
  pip:
    name=selenium
    state=latest
    virtualenv="{{ virtualenv_directory }}"

- name: download phantomjs
  become_user: root
  unarchive:
    src: "{{ phantomjs_archive }}"
    copy: no
    dest: "/opt"
    owner: "{{ cl_user }}"
    group: "{{ cl_user }}"
    creates: "/opt/phantomjs-{{ phantomjs_version }}-linux-x86_64"

- name: symlink phantomjs into /usr/bin
  become_user: root
  file:
    state: link
    path: "{{ phantomjs_symlink_root}}/phantomjs"
    src: "/opt/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs"
    owner: "{{ cl_user }}"
    group: "{{ cl_user }}"
