---
######### Not cloning CL...
- debug: msg="Doing minimal CL bootstrapping..."

- name: download CourtListener requirements.txt to bootstrap virtualenv
  get_url:
    url=https://raw.githubusercontent.com/freelawproject/courtlistener/master/requirements.txt
    dest=/tmp/requirements.txt

- name: pip install CourtListener requirements
  become_user: "{{ cl_user }}"
  pip:
    requirements=/tmp/requirements.txt
    virtualenv="{{ virtualenv_directory }}"
