#!/usr/bin/env ansible-playbook
---
# Update an existing FreeLawBox system
- hosts: dev
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    # if using an apt proxy, such as apt-cacher-ng, uncomment below
    # and set the variables defined in ./roles/net-cache/defaults/main.yml
    # as needed.
    #use_apt_cache: true
    # if using devpi server, uncomment below and set the variables
    # defined in ./roles/net-cache/defaults/main.yml as needed
    #use_devpi_cache: true
    installing_courtlistener: yes
    courtlistener_directory: /var/www/courtlistener
    virtualenv_directory: /home/vagrant/.virtualenvs/courtlistener
    cl_user: vagrant
  roles:
    - net-cache
    - ubuntu-trusty
    - vagrantbox
    - courtlistener
