# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404"

  config.vm.network "forwarded_port", guest: 8000, host: 8888
  config.vm.network "forwarded_port", guest: 8983, host: 8999

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = false
    vb.memory = "2048"
  end

end
