#!/usr/bin/env ansible-playbook
---
# Update an existing FreeLawBox system
- hosts: dev
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    #-----------------------------------------------
    use_apt_cache: true
    use_devpi_cache: true
    use_most_as_pager: true
    build_deb_packages: true
    redis_archive: /vagrant/extra/redis-stable.tar.gz
    timezone:
      hwclock: UTC
      name: US/Central
    #-----------------------------------------------
    installing_courtlistener: yes
    courtlistener_directory: /var/www/courtlistener
    cl_pg_password: your-password
    virtualenv_directory: /home/vagrant/.virtualenvs/courtlistener
    celery_user: vagrant
    redis_user: vagrant
    pg_user: vagrant
    solr_user: vagrant
    solr_version: 4.10.4
    solr_cores:
      - collection1
      - audio
      - opinion
      - recap
      - person
    ocr_user: vagrant
    cl_user: vagrant
  roles:
    - net-cache
    - ubuntu-trusty
    - vagrantbox
    - schroot
    - redis
    #- celery
    #- role: postgres
    #  tags:
    #    - postgres
    #- solr
    #- ocr
    #- courtlistener
